### ISSUE TITLE
Request - Exporting the TGT to disk

### ISSUE THREAD

**Issue by jsdhasfedssad** [Dec0ne/KrbRelayUp#15]
Hi. Thank you for this tool! I am testing obfuscation of this binary and while your tool evades Defender afterwards, CMD is not spawned. Or perhaps the service is not started. There are no errors in the output from the tool. I also tried setting "binpath" to "net user test Password123! /add && net localgroup Administrators test /add" but that also does not work. If the tool could write the TGT to disk I could use that instead of relying on having RDP access and features that may not be compatible with obfuscation. Would that be something you would be interested in adding?

**Comment by Dec0ne** [comment]
I added **--Verbose** flag which will display all the tickets generated with this tool as base64 for further use.
Thanks for the suggestion.
