### ISSUE TITLE
running relay

### ISSUE THREAD

**Issue by Morgandri1** [Dec0ne/KrbRelayUp#4]
Hello!

the relay seems to work fine until getting to `register COM server`, where it asks for firewall access. 

how do i get around it?

**Comment by Dec0ne** [comment]
Disable the firewall if its a home lab environment for testing. This most likely should not be an issue in real-life situations.
[Referring you to the original tool KrbRelay by @Cube0x0 where he explains this.](https://github.com/cube0x0/KrbRelay#:~:text=There%20may%20be%20difficulties%20with%20Server%20OS%20in%20lab%20environments%20because%20of%20the%20firewall%20blocking%20the%20OXID%20resolver%20however%2C%20this%20will%20most%20likely%20not%20be%20an%20issue%20during%20real%20life%20engagements)

**Comment by Morgandri1** [comment]
im using a standard version of win10 for edu but the firewall still comes up.

**Comment by wdormann** [comment]
In my testing, a firewall dialog comes up, but it can safely be ignored.
